# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxIssuesViewer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxIssuesViewer
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.0'
  pod 'RxAlamofire'
end
